# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - uses: Gufderald/git-remote-pull@main
        with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
          target-url: ${{ secrets.TARGET_URL }}
        # Such as wangchucheng
          target-username: ${{ secrets.TARGET_USERNAME }}
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS_TOKEN }}
          target-token: ${{ secrets.TARGET_TOKEN }}
